### ISSUE TITLE
error with trainStructureTransfer.py

### ISSUE THREAD

**Issue by dvschultz** [VITA-Group/ShapeMatchingGAN#14]
I get an error when trying the example trainStructureTransfer.py command listed in the README:

```
Traceback (most recent call last):
  File "trainStructureTransfer.py", line 89, in <module>
    main()
  File "trainStructureTransfer.py", line 35, in main
    Xl, X, _, Noise = load_style_image_pair(opts.style_name, scales, netSketch, opts.gpu)
  File "/content/ShapeMatchingGAN/src/utils.py", line 119, in load_style_image_pair
    Noise = torch.tensor(0).float().repeat(1, 1, 1).expand(3, ori_ht, ori_wd)
TypeError: expand(): argument 'size' must be tuple of ints, but found element of type float at pos 3
```

**Comment by dvschultz** [comment]
ah looks like these are float errors from python2 to 3. If you’d like to make this python3 compliant let me know and I can submit a PR.

**Comment by williamyang1991** [comment]
I would appreciate it if you can help fix this compatibility problem 👍

**Comment by dvschultz** [comment]
great I’ll submit something this week

**Comment by sevaroy** [comment]
I have the same issue

**Comment by williamyang1991** [comment]
> I have the same issue
Maybe you can just change 'ori_wd = ori_wd / 2' to 'ori_wd = int(ori_wd / 2)' in utils.py.
It there are similar issue, you can just use this solution to translate the float number to int number.

**Comment by sevaroy** [comment]
> > I have the same issue
> > Maybe you can just change 'ori_wd = ori_wd / 2' to 'ori_wd = int(ori_wd / 2)' in utils.py.
> > It there are similar issue, you can just use this solution to translate the float number to int number.

I replace  'ori_wd = int(ori_wd / 2)'  to  'ori_wd = ori_wd / 2'  in utils.py 115 line.
but still not work

**Comment by williamyang1991** [comment]
> > > I have the same issue
> > > Maybe you can just change 'ori_wd = ori_wd / 2' to 'ori_wd = int(ori_wd / 2)' in utils.py.
> > > It there are similar issue, you can just use this solution to translate the float number to int number.
> 
> I replace 'ori_wd = int(ori_wd / 2)' to 'ori_wd = ori_wd / 2' in utils.py 115 line.
> but still not work

Can you tell me the detailed error information just as dvschultz did?

**Comment by sevaroy** [comment]
File "trainStructureTransfer.py", line 89, in <module>
    main()
  File "trainStructureTransfer.py", line 40, in main
    for i in range(opts.Straining_num/opts.batchsize):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by sevaroy** [comment]
> > > > I have the same issue
> > > > Maybe you can just change 'ori_wd = ori_wd / 2' to 'ori_wd = int(ori_wd / 2)' in utils.py.
> > > > It there are similar issue, you can just use this solution to translate the float number to int number.
> > 
> > 
> > I replace 'ori_wd = int(ori_wd / 2)' to 'ori_wd = ori_wd / 2' in utils.py 115 line.
> > but still not work
> 
> Can you tell me the detailed error information just as dvschultz did?

  File "trainStructureTransfer.py", line 89, in <module>
    main()
  File "trainStructureTransfer.py", line 40, in main
    for i in range(opts.Straining_num/opts.batchsize):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by williamyang1991** [comment]
> > > > > I have the same issue
> > > > > Maybe you can just change 'ori_wd = ori_wd / 2' to 'ori_wd = int(ori_wd / 2)' in utils.py.
> > > > > It there are similar issue, you can just use this solution to translate the float number to int number.
> > > 
> > > 
> > > I replace 'ori_wd = int(ori_wd / 2)' to 'ori_wd = ori_wd / 2' in utils.py 115 line.
> > > but still not work
> > 
> > 
> > Can you tell me the detailed error information just as dvschultz did?
> 
> File "trainStructureTransfer.py", line 89, in
> main()
> File "trainStructureTransfer.py", line 40, in main
> for i in range(opts.Straining_num/opts.batchsize):
> TypeError: 'float' object cannot be interpreted as an integer

This one helps:
https://stackoverflow.com/questions/19824721/i-keep-getting-this-error-for-my-simple-python-program-typeerror-float-obje

**Comment by sevaroy** [comment]
> > > > > > 我有同樣的問題，
> > > > > > 也許您可以在utils.py中將“ ori_wd = ori_wd / 2”更改為“ ori_wd = int（ori_wd / 2）”。
> > > > > > 那裡也有類似的問題，您可以使用此解決方案將浮點數轉換為整數。
> > > > 
> > > > 
> > > > 我在utils.py 115行中將'ori_wd = int（ori_wd / 2）'替換為'ori_wd = ori_wd / 2'。
> > > > 但仍然行不通
> > > 
> > > 
> > > 您能像dvschultz一樣告訴我詳細的錯誤信息嗎？
> > 
> > 
> > 文件“ trainStructureTransfer.py”，位於
> > main（）的第89行文件“ trainStructureTransfer.py”，位於main（）的
> > 第40行，
> > 對於i在範圍內（opts.Straining_num / opts.batchsize）：
> > TypeError：“ float”對像不能解釋為一個整數
> 
> 這有助於：[https](https://stackoverflow.com/questions/19824721/i-keep-getting-this-error-for-my-simple-python-program-typeerror-float-obje) :
> [//stackoverflow.com/questions/19824721/i-keep-getting-this-error-for-my-simple-python-program-typeerror-float-obje](https://stackoverflow.com/questions/19824721/i-keep-getting-this-error-for-my-simple-python-program-typeerror-float-obje)

it work for me .
thanks a lot

**Comment by sevaroy** [comment]
Hi 

I have other issue

Traceback (most recent call last):
  File "trainStructureTransfer.py", line 89, in <module>
    main()
  File "trainStructureTransfer.py", line 43, in main
    opts.Sanglejitter, opts.subimg_size, opts.subimg_size)
  File "C:\Users\user\Desktop\synbolstyle\src\XXXX\ShapeMatchingGAN-master\src\utils.py", line 161, in cropping_training_batches
    input[:,0] = torch.clamp(input[:,0] + noise[:,0], -1, 1)
RuntimeError: The size of tensor a (256) must match the size of tensor b (254) at non-singleton dimension 2
