### ISSUE TITLE
higher resolution

### ISSUE THREAD

**Issue by dvschultz** [VITA-Group/ShapeMatchingGAN#15]
I assume if I retrain the sketch network on higher resolution samples and then train both the structure and texture models on ~same sized samples I can achieve a higher resolution output? Should I also modify the `--subimg_size` option?

Have you tried this or seen any issues with network size maxing out the GPU?

**Comment by williamyang1991** [comment]
I think you're right. To obtain HR results, HR images should be used for training. (I think another way might be to obtain LR results and then use SuperResolution methods to obtain HR images)
I think the --subimg_size mainly depends on the size of structure/texture patterns. If those are quite large in your HR images, then the --subimg_size should be increased correspondingly to make the network fully perceive the key patterns.

Sorry, I'm not sure if there are issues with network size maxing out the GPU. I haven't tried it before.

**Comment by dvschultz** [comment]
no worries, this is really helpful. thanks! I _think_ the subimg_size param will actually determine the GPU usage, and I think it can be brought up a bit based on my previous work. Will give it a shot and let you know!

**Comment by williamyang1991** [comment]
Looking forward to it :)
