### ISSUE TITLE
What license do you have?

### ISSUE THREAD

**Issue by gexahedron** [VITA-Group/ShapeMatchingGAN#20]
Hi!

There's a default license for github projects
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

It is kind of restricted.
Do you plan to add a license to the code?

**Comment by williamyang1991** [comment]
Sorry for late reply
I have added a MIT license

**Comment by gexahedron** [comment]
thanks!
