### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by lance0515** [VITA-Group/ShapeMatchingGAN#21]
i have a question with training  Texture&Structure
when i training Texture or Structure, the input style should mask and original image both?(side by side)  or separate training?(Structure training (mask)) (texture training (original image))

**Comment by lance0515** [comment]
and another question about utils.text_image_preprocessing 
how do i use utils.text_image_preprocessing to  get distance-based mask 
sorry about this stupid question

**Comment by williamyang1991** [comment]
Use `load_image('your file name', 1)` to load black and white image and transform it into distance-based mask,
then use `save_image(img, 'your file name')` to save your distance-based mask.

---------------------------------------------
In `utils.py`
```
def load_image(filename, load_type=0):
    transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5],std=[0.5,0.5,0.5]),
    ])
    
    if load_type == 0:
        img = Image.open(filename)
    else:
        img = text_image_preprocessing(filename)
    img = transform(img)
        
    return img.unsqueeze(dim=0)

def save_image(img, filename):
    tmp = ((img.numpy().transpose(1, 2, 0) + 1.0) * 127.5).astype(np.uint8)
    cv2.imwrite(filename, cv2.cvtColor(tmp, cv2.COLOR_RGB2BGR))
```

**Comment by williamyang1991** [comment]
> i have a question with training Texture&Structure
> when i training Texture or Structure, the input style should mask and original image both?(side by side) or separate training?(Structure training (mask)) (texture training (original image))

Structure and texture can be trained seperately and independantly.
You image should be arranged like the following: mask & style (side by side)
https://raw.githubusercontent.com/VITA-Group/ShapeMatchingGAN/master/data/style/fire.png
