### ISSUE TITLE
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

### ISSUE THREAD

**Issue by liaoxiaojiao** [VITA-Group/ShapeMatchingGAN#23]
您好，当我运行test.py时出现
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0
是为什么呀

**Comment by williamyang1991** [comment]
以我的经验，可能是因为你输入的图像是png格式的，是32位不是24位的图像（多带了一个透明通道）？
如果真的是这个问题，你转成jpg的形式应该可以了
