### ISSUE TITLE
why training for 3 steps?

### ISSUE THREAD

**Issue by caihaunqai** [VITA-Group/ShapeMatchingGAN#38]
Hello, thanks for your excellent job. I wonder why we train in three steps rather than one? Is there any difference? Thank you.

**Comment by caihaunqai** [comment]
Thank you for your reply. I totally agree with your point of view. Maybe my expression is a little off before. I wonder why the training process of structure is divided into three steps. Is there any difference?

**Comment by williamyang1991** [comment]
Our Controllable ResBlock is inspired by [Deep Network Interpolation](https://xinntao.github.io/projects/DNI)
We just follow its implementation to 
step 1: first train one path of the network on one style scale 
step 2: copy this paper to another path and finetune this path on another style scale 
step 3: finetune both paths on multiple scales.

The idea behind it is that the finetuned model and the original model have correlated  features. 
The linear interpolation in the parameter space (in our paper is the feature space) of two correlated networks leads to  continuous imagery effect transition.

**Comment by caihaunqai** [comment]
Thank you very much.
