### ISSUE TITLE
Is distance-based process necessary?

### ISSUE THREAD

**Issue by caihaunqai** [VITA-Group/ShapeMatchingGAN#39]
Hello, Thank you for your excellent job. I wonder the the importance of text distance postprocess.  I find that the training text datasets are images with distance postprocess. But it is not used if we do not use "Lgly", which is based on the choice of glyph_preserve. Besides, it is not selected by default in the training code. Thank you.

**Comment by williamyang1991** [comment]
Please refer to our CVPR paper [T-Effect](https://github.com/williamyang1991/Text-Effects-Transfer/) and AAAI paper [TET-GAN](https://github.com/williamyang1991/TET-GAN)

> As reported in (Yang et al. 2017), the spatial distribution of the texture in text effects is highly related to its distance from the
glyph, forming an effective prior for text effects transfer. To leverage this prior, we propose a distribution-aware preprocessing for the text image to directly feed our network with distance cues. As shown in Fig. 5, we extend the raw text image from one channel to three channels. The R channel is the original text image, while G channel and B channel are distance maps where the value of each pixel is its distance to the background black region and the foreground white glyph, respectively. Another advantage of the preprocessing is that our three-channel text images have much fewer saturated areas than the original ones, which greatly facilitates the extraction of valid features.

And here is an ablation study in our AAAI paper. Compare (b) and (c), the style is better transferred.
![image](https://user-images.githubusercontent.com/18130694/189030168-4a217e01-a9c1-47c7-b9ad-76ada9f1fbb9.png)

**Comment by caihaunqai** [comment]
Thank you
