### ISSUE TITLE
I find some problem

### ISSUE THREAD

**Issue by EndlessParadox1** [VITA-Group/ShapeMatchingGAN#41]
As  noted, the project was implemented by python27 & pytorch1.10, but in fact pytorch1.10 is only available in python version >=3.7, soI think it is actually 3.7 instead of 2.7.

**Comment by williamyang1991** [comment]
![image](https://github.com/VITA-Group/ShapeMatchingGAN/assets/18130694/c7b7a3cc-28a3-458f-9eef-f6dc0572ea06)
